databases:
  - name: mysite-db
    plan: free

services:
  - type: web
    name: mysite
    env: ruby
    buildCommand: "bundle install --path vendor/bundle --without development:test && bundle exec rake assets:precompile"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite-db
          property: connection_url